# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('potholes_site', '0002_search_zipcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Hyde Park', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Neighborhood_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='potholes_site.Neighborhood1')),
                ('Neighborhood_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='potholes_site.Neighborhood2')),
                ('Neighborhood_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='potholes_site.Neighborhood3')),
            ],
        ),
        migrations.RenameField(
            model_name='search',
            old_name='zipcode',
            new_name='zip_code',
        ),
        migrations.AddField(
            model_name='search',
            name='urgency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='potholes_site.Urgency'),
        ),
        migrations.AlterField(
            model_name='search',
            name='end_date',
            field=models.DateField(default='MM/DD/YYYY'),
        ),
        migrations.AlterField(
            model_name='search',
            name='start_date',
            field=models.DateField(default='MM/DD/YYYY'),
        ),
        migrations.AlterField(
            model_name='urgency',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
