# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potholes_site', '0003_auto_20160218_2315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ward',
        ),
        migrations.AlterField(
            model_name='neighborhood1',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='search',
            name='status',
            field=models.CharField(default='Open', max_length=10),
        ),
        migrations.AlterField(
            model_name='search',
            name='urgency',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='Urgency',
        ),
    ]
